# MySQL Database

SQL (Structured Query Language) - это язык программирования, который используется для работы с реляционными базами данных. SQL позволяет создавать, изменять, удалять и извлекать данные из базы данных. Он используется в различных областях, таких как банковское дело, медицинские учреждения, интернет-магазины и многие другие.

MySQL - это система управления реляционными базами данных, которая использует SQL для управления данными. MySQL является одним из наиболее популярных серверов баз данных в мире и широко используется веб-разработчиками. MySQL является бесплатным и открытым исходным кодом, что означает, что его можно свободно загружать, использовать и изменять.

MySQL позволяет создавать базы данных, таблицы и связи между ними, а также добавлять, изменять и удалять данные. Он также поддерживает многопользовательский доступ и безопасность для защиты ваших данных. MySQL можно использовать с различными языками программирования, такими как PHP, Python, Java и другие.

В целом, SQL и MySQL являются важными инструментами для хранения, управления и извлечения данных, и их использование в современном мире является необходимым для различных видов приложений и сервисов.

In [33]:
import mysql.connector
import pandas as pd
import csv
import codecs as cs

Предварительно необходимо инициализировать базу данных, например  ```school```

In [26]:
# Подключение к MySQL
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="qwer1324",
  database="school"
)
mycursor = mydb.cursor()

In [ ]:

# создаем базу данных
mycursor.execute("CREATE DATABASE school")
# Выбираем базу данных 
mycursor.execute("USE school")
# Создаём таблицу
mycursor.execute("CREATE TABLE students (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, age INT)")

In [ ]:
# Добавление значений в таблицу
mycursor.execute("INSERT into students VALUES(2, 'Matvey Isupov', 16)")

In [137]:
# Выполнение запроса на выборку данных из таблицы
mycursor.execute("SELECT * FROM students")
# Получение результатов запроса
myresult = mycursor.fetchall()
# Вывод результатов на экран
for row in myresult:
  print(row)

(2, 'Matvey Isupov', 16)
(3, 'Vsevolod Buzinskiy', 16)
(4, 'Arkhip Moskovskiy', 17)
(5, 'Anna Boldyreva', 16)

In [68]:
mycursor.execute("DELETE FROM students WHERE id = 3")

### CSV & MySQL

In [134]:
data = pd.DataFrame({
    'name': ["Vsevolod Buzinskiy", "Arkhip Moskovskiy", "Anna Boldyreva"],
    'age' : [16, 17, 16]
})


def data_prepare(data):
    temp_name = []
    temp_age = []
    temp = []
    for i in data['age']:
        temp_age.append(i) 

    for l in data['name']:
        temp_name.append(l)


    for name, age in zip(temp_name, temp_age):
        temp.append(dict([(name, age)]))

    return temp


def upload(data):
    for index in enumerate(data):
        # print(f"({int(index[0] + 3)}, {str(list(index[1].keys())[0])}, {int(list(index[1].values())[0])})")

        mycursor.execute(f"INSERT into students VALUES({int(index[0] + 3)}, '{str(list(index[1].keys())[0])}', {int(list(index[1].values())[0])})")
    mycursor.close
    
    return print('successfully uploaded')

prepared_data = data_prepare(data)
upload(prepared_data)

def delete(id, name=None, age=None):
    mycursor.execute(f"DELETE from students WHERE id = {id}")
    return print(f'successfully deleted {id}')



# print(data_prepare(data))
# print(type(df['age']))

successfully uploaded

In [136]:
def delete(id, name=None, age=None):
    mycursor.execute(f"DELETE from students WHERE id = {id}")
    return print(f'successfully deleted {id} id')

delete(1)

successfully deleted 1